In [1]:
import pandas as pd

In [2]:
watchlist_df = pd.read_csv('Watchlist.csv') # read the dataset as a DataFrame into a variable named 'watchlist'

In [3]:
watchlist_df.head() # Preview top 5 rows using head()

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
0,1,tt0332280,8/13/2015,8/13/2015,NaN,The Notebook,https://www.imdb.com/title/tt0332280/,movie,7.8,123.0,2004,"Drama, Romance",495765,5/20/2004,Nick Cassavetes,10.0,12/8/2016
1,2,tt0281358,8/13/2015,8/13/2015,NaN,A Walk to Remember,https://www.imdb.com/title/tt0281358/,movie,7.4,101.0,2002,"Drama, Romance",193482,1/23/2002,Adam Shankman,8.0,12/8/2016
2,3,tt0111161,7/23/2016,7/23/2016,NaN,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/,movie,9.3,142.0,1994,Drama,2213171,9/10/1994,Frank Darabont,10.0,12/8/2016
3,4,tt0110912,7/23/2016,7/23/2016,NaN,Pulp Fiction,https://www.imdb.com/title/tt0110912/,movie,8.9,154.0,1994,"Crime, Drama",1737531,5/21/1994,Quentin Tarantino,5.0,7/21/2017
4,5,tt0137523,7/23/2016,7/23/2016,NaN,Fight Club,https://www.imdb.com/title/tt0137523/,movie,8.8,139.0,1999,Drama,1765736,9/10/1999,David Fincher,8.0,7/21/2017

In [4]:
watchlist_df.tail() # preview bottom 5 rows using tail()

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
995,996,tt5241194,4/7/2020,4/7/2020,NaN,Azwaj Taeeshoon,https://www.imdb.com/title/tt5241194/,movie,4.2,98.0,1976,Comedy,40,12/31/1976,Neyazi Mustafa,NaN,NaN
996,997,tt2300871,4/7/2020,4/7/2020,NaN,El-Bahth an El-Mataeb,https://www.imdb.com/title/tt2300871/,movie,4.5,NaN,1975,"Comedy, Romance",56,NaN,Mahmood Farid,NaN,NaN
997,998,tt0382010,4/7/2020,4/7/2020,NaN,Ellembi,https://www.imdb.com/title/tt0382010/,movie,6.2,100.0,2002,Comedy,1053,12/31/2002,Wael Ihsan,NaN,NaN
998,999,tt0422319,4/7/2020,4/7/2020,NaN,Ghabi mino fih,https://www.imdb.com/title/tt0422319/,movie,5.9,NaN,2004,Comedy,839,7/27/2004,Rami Imam,7.0,4/7/2020
999,1000,tt6659088,4/7/2020,4/7/2020,NaN,Etnen Ala El Tareeq,https://www.imdb.com/title/tt6659088/,movie,4.8,NaN,1984,Drama,52,6/30/1984,Hasan Youssef,NaN,NaN

In [5]:
watchlist_df.shape # the number of rows x cols

(1000, 17)

In [ ]:
#This function tells us that there are 1000 rows and 17 columns in the dataset

In [ ]:
#Let's use describe( ) method to understand the numerical attributes in the data
#describe( ) shows the basic statistical summaries of numerical attributes in the data.

In [6]:
watchlist_df.describe()

,Position,Description,IMDb Rating,Runtime (mins),Year,Num Votes,Your Rating
count,1000.000000,0.0,1000.000000,958.000000,1000.000000,1.000000e+03,665.000000
mean,500.500000,NaN,7.168700,112.107516,2003.442000,2.279540e+05,6.912782
std,288.819436,NaN,1.003473,33.375103,14.668599,3.081640e+05,1.226552
min,1.000000,NaN,3.400000,7.000000,1916.000000,5.000000e+00,1.000000
25%,250.750000,NaN,6.600000,98.000000,2000.000000,1.582950e+04,6.000000
50%,500.500000,NaN,7.300000,113.000000,2007.000000,1.146350e+05,7.000000
75%,750.250000,NaN,7.900000,127.000000,2012.000000,3.169092e+05,8.000000
max,1000.000000,NaN,9.500000,366.000000,2019.000000,2.213171e+06,10.000000

In [ ]:
#Some insights from the description table

#The min and max values in ‘Year’ depict the minimum and maximum release years. We can see that the dataset contains movies from 1916 to 2019.
#The average IMDb rating for the movies in this dataset is about 7.2 and the minimum IMDb rating is 3.4 and the maximum IMDb rating is 9.5

In [22]:
# check null values
watchlist_df.isnull().sum()

Position          0.0
Const             0.0
Created           0.0
Modified          0.0
Description       0.0
Title             0.0
URL               0.0
Title Type        0.0
IMDb Rating       0.0
Runtime (mins)    0.0
Year              0.0
Genres            0.0
Num Votes         0.0
Release Date      0.0
Directors         0.0
Your Rating       0.0
Date Rated        0.0
dtype: float64

In [7]:
watchlist_df.describe(include='object')

,Const,Created,Modified,Title,URL,Title Type,Genres,Release Date,Directors,Date Rated
count,1000,1000,1000,1000,1000,1000,999,987,950,665
unique,1000,440,440,999,1000,7,340,920,606,399
top,tt0265208,12/8/2016,12/8/2016,The Lion King,https://www.imdb.com/title/tt1295085/,movie,"Drama, Romance",9/2/2016,Charles Chaplin,12/8/2016
freq,1,233,233,2,1,926,68,4,12,54

In [8]:
watchlist_df.columns # The column names in the data can be viewed by using 'columns'

Index(['Position', 'Const', 'Created', 'Modified', 'Description', 'Title',
       'URL', 'Title Type', 'IMDb Rating', 'Runtime (mins)', 'Year', 'Genres',
       'Num Votes', 'Release Date', 'Directors', 'Your Rating', 'Date Rated'],
      dtype='object')

In [9]:
watchlist_df[['Title','IMDb Rating','Year','Genres']]

                        Title  IMDb Rating  Year           Genres
0                The Notebook          7.8  2004   Drama, Romance
1          A Walk to Remember          7.4  2002   Drama, Romance
2    The Shawshank Redemption          9.3  1994            Drama
3                Pulp Fiction          8.9  1994     Crime, Drama
4                  Fight Club          8.8  1999            Drama
..                        ...          ...   ...              ...
995           Azwaj Taeeshoon          4.2  1976           Comedy
996     El-Bahth an El-Mataeb          4.5  1975  Comedy, Romance
997                   Ellembi          6.2  2002           Comedy
998            Ghabi mino fih          5.9  2004           Comedy
999       Etnen Ala El Tareeq          4.8  1984            Drama

[1000 rows x 4 columns]

In [10]:
watchlist_df['Title'].value_counts()

The Lion King                      2
The Notebook                       1
The Killing of a Sacred Deer       1
Babel                              1
Gone Baby Gone                     1
                                  ..
The Mountain Between Us            1
Khamsa Bab                         1
Good Bye Lenin!                    1
Joker                              1
The Girl with the Dragon Tattoo    1
Name: Title, Length: 999, dtype: int64

In [11]:
watchlist_df['Title'].unique()

array(['The Notebook', 'A Walk to Remember', 'The Shawshank Redemption',
       'Pulp Fiction', 'Fight Club', 'Forrest Gump', 'Gladiator',
       'Braveheart', 'Eternal Sunshine of the Spotless Mind',
       'Good Will Hunting', 'Up', 'A Beautiful Mind', 'The Message',
       'Into the Wild', 'The Revenant', 'Catch Me If You Can',
       'Pirates of the Caribbean: The Curse of the Black Pearl',
       'Kanyamakan', 'Casanegra', 'V for Vendetta', 'The Kid',
       'The Truman Show', 'The Godfather', 'Inception', 'American Beauty',
       "Le fabuleux destin d'Am�lie Poulain", 'Room', '12 Years a Slave',
       'Ce que le jour doit � la nuit', 'Crazy, Stupid, Love.',
       'Divergent', 'Fury', 'Ghost', 'The Girl Next Door', 'Ondine',
       'P.S. I Love You', 'Pas son genre', 'Remember Me', 'Safe Haven',
       "She's Out of My League", 'The Age of Adaline',
       'The Sleeping Dictionary', "The Time Traveler's Wife", 'Titanic',
       'Spartacus: Blood and Sand', 'Spartacus: Gods of the Arena',
       'Tristan + Isolde', 'The Twilight Saga: New Moon',
       'The Twilight Saga: Eclipse', 'Twilight', 'The Hunger Games',
       'Tres metros sobre el cielo', 'Tengo ganas de ti', 'Alexander',
       '1612: Khroniki smutnogo vremeni', '127 Hours', '10,000 BC',
       'Zootopia', 'Undisputed III: Redemption',
       'Undisputed II: Last Man Standing', 'Undisputed', 'Troy',
       'Treasure Island', 'Tracers', 'Vicky Cristina Barcelona',
       'Warcraft', 'Wild Things', 'Spread', 'Thor',
       'The Theory of Everything', 'The Vow', 'The Seasoning House',
       'The Scorpion King', 'The Pursuit of Happyness',
       'The Perfect Storm', 'The Other Boleyn Girl', 'Le nom des gens',
       'The Mummy Returns',
       'The Lord of the Rings: The Fellowship of the Ring',
       'The Longest Ride', 'The Legend of Tarzan',
       'The Legend of Hercules', 'The Last Legion', 'Solomon Kane',
       'The Karate Kid', 'The Hot Chick', 'The Hitcher', 'The Grey',
       'The Finest Hours', 'The Experiment', 'The Expendables',
       'The Expendables 2', 'The Expendables 3', 'The Dictator',
       'The Broken Circle Breakdown', 'The 40 Year Old Virgin', 'Tangled',
       '13 game sayawng', 'Dalkomhan insaeng', 'African Cats',
       'All Is Lost', 'Arena', 'Atonement', 'Avatar', 'Bangrajan',
       'Bang Rajan 2', 'Bangkok Adrenaline', 'Battle for Haditha',
       'Before We Go', 'The Rundown', 'Blood Diamond', 'Blue Valentine',
       'Brick Mansions', 'Cast Away', 'Kimssi pyoryugi', 'Centurion',
       'Chaos', 'Charlie St. Cloud',
       "Chroniques sexuelles d'une famille d'aujourd'hui",
       'I due superpiedi quasi piatti', 'Cruel Intentions',
       "Da Vinci's Demons", 'Water for Elephants', 'Deep in the Valley',
       'Don Jon', 'Drop Dead Sexy', 'Earth', 'Eden', 'Enter the Dragon',
       'Everest', 'Exit Marrakech', 'Fanny och Alexander',
       'Far from the Madding Crowd', 'Generation Iron', 'Gun Woman',
       'Hannibal Rising', "Harry Potter and the Sorcerer's Stone",
       'Harry Potter and the Prisoner of Azkaban',
       'Harry Potter and the Goblet of Fire', 'Her', 'Hercules',
       'Hot Pursuit', 'Hunger', 'I Now Pronounce You Chuck & Larry',
       'I Love You, Beth Cooper', 'Ice Age', 'If I Stay',
       'In the Heart of the Sea', 'Indig�nes', 'Intouchables',
       "Jeux d'enfants", 'Jobs', 'Johnny English', 'Joshua',
       'King Arthur', 'King Kong',
       'In the Name of the King: A Dungeon Siege Tale',
       'Kingdom of Heaven', 'The Meerkats', 'The Bourne Identity',
       'Night at the Museum', 'Le dernier trappeur',
       'Legends of the Fall', 'L�on', 'Defiance', 'Les Mis�rables',
       'Lost in Translation', 'Love & Other Drugs', 'Ma premi�re fois',
       'Machete', 'Made of Honor', 'Mal�na', 'Home Alone',
       'Man on a Ledge', 'Marina',
       'Master and Commander: The Far Side of the World',
       'Million Dollar Baby', 'Modern Times', 'My Blueberry Nights',
       'Final Destination 2', 'Final Destination 3',
       'Final Destination 5', 'The Final Destination', 'Ninja Assassin',
       'Nos jours heureux', 'Oldeuboi', 'One Day', 'Out of the Furnace',
       'Prime', 'Pirates of the Caribbean: On Stranger Tides',
       "Pirates of the Caribbean: At World's End",
       "Pirates of the Caribbean: Dead Man's Chest", 'Pompeii',
       'Prince of Persia: The Sands of Time', 'Jurassic Park',
       'Rescue Dawn', 'Salt', 'Sanctum', 'No Strings Attached',
       'Snow White and the Huntsman', 'Stand by Me', 'Swimfan',
       '300: Rise of an Empire', '300', 'Ahasees', 'Khamsa',
       'Rock the Casbah', "Les oubli�s de l'histoire", 'Snowden',
       'Ben-Hur', 'Just Go with It', 'Mechanic: Resurrection',
       'The Great Gatsby', 'The Perks of Being a Wallflower',
       'The Curious Case of Benjamin Button', 'Hassan wa Morcus',
       "Alzheimer's", 'Al-irhab wal kabab', 'X-Large', 'Omaret yakobean',
       'El-sefara fi El-Omara', 'Morgan Ahmed Morgan', 'Al-irhabi',
       'Amir El Zalam', 'El tagrubah el danemarkiyyah',
       'Aris min geha amneya', 'Toyour elzalam', 'Salam Ya Sahby',
       'Shams elzanaty', "Allaeb ma'a alkebar", 'Ehna Betoa El Otobees',
       'El Noom fi el Asal', 'Al-avokato', 'Hata la yatir al dokhan',
       'Al-motasaul', 'Hob Fi El-Zinzana', 'Al-ghoul', 'Ala bab el wazir',
       'Ragol Fakad Aklah', 'Al-Baadh Yathhab Lil Maathoun Maratain',
       'El Mansy', 'Al-mouled', 'Meen Fena El-Haramy?', 'Al-halfout',
       "Athkiya' laken aghbiya'", 'Elwad mahrous betaa alwazir',
       'Hanafy al-obaha', 'Ramadan fawq al-borkan',
       'Shaaban Taht El-Sifr', 'Ragab Fawq Safeeh Sakhin',
       'Zoj taht al-talab', 'Jazeerat al-shaytan', 'El-Mahfaza Maaya',
       'Mamnou Fi Laylat El-Dokhla', 'Antar Shayel Saifoh',
       'Hello America', 'Al-Azwag Al-Shayateen', 'Bobbos',
       'The Walking Dead', 'Insurgent', 'Thor: The Dark World', 'Focus',
       'Dawn of the Planet of the Apes', 'La vita � bella', 'Se7en',
       'The Pianist', 'Q', 'Batal min warak', 'Intimacy',
       'Mr. & Mrs. Smith', 'Suburban Secrets', 'The Incredible Hulk',
       "Aasef ala el-iz'ag", 'Excuse My French', 'World War Z',
       'Silver Linings Playbook', 'The Town', 'Death Race',
       'The Last Samurai', 'Never Back Down',
       'Harold & Kumar Go to White Castle', 'Love Actually',
       'American Gangster', 'Unbroken', 'Cidade de Deus',
       "De rouille et d'os", 'The Silence of the Lambs', 'Hotaru no haka',
       'Aldada Dodi', 'Baheb el cima', 'Africano', 'Awqat faragh',
       'Gegen die Wand', 'Life of Pi', "Schindler's List",
       'Al-bahth an fadiha', 'Marock', 'Les chevaux de Dieu', 'Zero',
       'Much Loved', 'Ali Zaoua, prince de la rue', 'Road to Kabul',
       'Death for Sale', 'Ratatouille', 'Al-Mohem El-Hob', "24 Saa'a Hob",
       'Intakhebo El-Doctoor Sulieman Abdel Basset', 'Dogville',
       'Karakon fe al-sharea', 'Drive', 'Al-Mashbouh',
       'Esabat Hamada Wa Toto', 'Ehtares min Alkhot', 'Unfaithful',
       'Before Sunrise', 'The Lord of the Rings: The Two Towers',
       'Before Sunset', 'Before Midnight', 'Assal Eswed',
       'L.A. Confidential', 'La meglio giovent�', 'Akeelah and the Bee',
       'El harrif', 'El-Gaheem', 'The Departed',
       'The Twilight Saga: Breaking Dawn - Part 1',
       'The Twilight Saga: Breaking Dawn - Part 2', 'Pinocchio',
       'Kit Kat', 'Der Untergang', 'Al-nemr wa al-ontha', "Al Baree'",
       'Underworld', 'El-Keif', 'Closer', 'Little Children', 'Attila',
       'Little Man', "Big Momma's House", 'Alf Mabrouk',
       'Midnight in Paris', 'Khamsa Bab', 'Waheda Bewaheda',
       'Olympus Has Fallen', 'Match Point', 'Ana wa hua wa hia',
       'Knocked Up', 'Memento', 'Un proph�te', '3 Idiots', 'Booha',
       'Revolutionary Road', 'Tom yum goong', 'Celda 211', '[Rec]',
       'Reel Bad Arabs: How Hollywood Vilifies a People', 'Babel',
       'Les anges de Satan', "L'amante du rif", 'Al Khattaf',
       'EX-Shamkar', 'Les bandits', 'Un Marocain � Paris', 'Ong-bak',
       'Das Boot', 'Old School', 'Deep Blue Sea', 'Prisoners',
       'Pride & Prejudice', 'Catwoman', 'Garfield: A Tale of Two Kitties',
       'Shutter Island', 'Bakhit wa Adeela 2', 'Tonari no Totoro',
       'Zarf Tarek', 'Ghost Ship', 'Amours voil�es',
       '� la recherche du mari de ma femme', 'La symphonie marocaine',
       'The Sixth Sense', 'The Matrix', 'The Bourne Ultimatum',
       'The Wolf of Wall Street', 'Al-ris�lah', 'The Reader',
       'The Dark Knight', 'The Forbidden Kingdom',
       'The Place Beyond the Pines', 'Training Day',
       'Message in a Bottle', 'A Nightmare on Elm Street',
       'Beauty and the Beast', 'The Lion King', 'Batman Begins',
       'The Mask of Zorro', 'Bandidas', 'The Prestige', 'The Gold Rush',
       'The Great Dictator', 'City Lights', 'Gone Girl',
       'Mad Max: Fury Road', 'Edward Scissorhands', 'The Circus',
       'Inside Out', 'The Story of God with Morgan Freeman', 'Shrek',
       'Perfume: The Story of a Murderer', 'Grown Ups 2',
       'The Jungle Book', 'Mr. Deeds', 'Khally Balak Men Geranak',
       'Snatch', 'The Way Back', 'Southpaw', 'The Eagle', 'Keda Reda',
       'El-Talatah Yishtaghaloonha', 'Spider-Man', 'Spider-Man 2',
       'The Mummy', 'Spider-Man 3', 'Toy Story',
       'Lock, Stock and Two Smoking Barrels', 'Eight Below',
       'The Shallows', "La leggenda del pianista sull'oceano", 'Fracture',
       'Mary and Max', 'Eskiya', 'Carol', 'Saving Private Ryan',
       'Escape Plan', 'Django Unchained', '2012', 'Boyka: Undisputed IV',
       'Rise of the Planet of the Apes', 'La La Land',
       'Final Destination', 'Lost', 'Prison Break', 'Mononoke-hime',
       'Kaze no tani no Naushika', 'The Godfather: Part II',
       'Sen to Chihiro no kamikakushi', 'Goodfellas',
       'Tenk� no shiro Rapyuta', 'Argo', 'The English Patient',
       'Funny Games', 'Eden Lake', 'Fear the Walking Dead', 'Saw',
       'Hauru no ugoku shiro', "One Flew Over the Cuckoo's Nest",
       'The Usual Suspects', 'American History X',
       'Jodaeiye Nader az Simin', 'Pippi Longstocking', 'Split',
       'Maison close', 'Meitantei Conan', 'Poketto monsut�', 'Naruto',
       'Dragon Ball Z: Doragon b�ru zetto', 'Inglourious Basterds',
       'The Bourne Supremacy', 'Blow', 'Interstellar', 'Exam',
       'A Clockwork Orange', 'The Imitation Game', 'Moana', 'Asi',
       'Ihlamurlar altinda', 'Cube', 'The Road', 'Jaws',
       "Hachi: A Dog's Tale", 'Meitantei Conan: Bek� Sutor�to no b�rei',
       'La habitaci�n de Fermat', 'WALL�E', 'Hacksaw Ridge', 'Hall Pass',
       'I Want Candy', 'Das Leben der Anderen', 'Killer Elite', 'Hidalgo',
       'The Green Mile', 'Requiem for a Dream', 'Monsters, Inc.',
       'Lo imposible', 'The Fighter', 'Moonrise Kingdom', 'Momentos',
       'Captain Phillips', 'Gran Torino', 'Whiplash', 'Vicky and Sam',
       '47 Meters Down', 'Griffin & Phoenix', 'Taxi Driver',
       'Kaze tachinu', '12 Angry Men', 'Green Zone',
       'How to Train Your Dragon',
       "Masdar: une cit� verte au pays de l'or noir", 'Human Planet',
       'Belle Epoque', 'Tracks', 'La cara oculta', 'Friday the 13th',
       'Lone Survivor', 'Chained', 'M�s sabe el diablo', 'Ke�d Ensa',
       'Mulholland Dr.', 'Brain on Fire', 'Y tu mam� tambi�n',
       'Yousuf e Payambar', 'Immortals', '12 Feet Deep',
       'Finding Forrester', 'The Girl with the Dragon Tattoo',
       'Dances with Wolves', 'The Maze Runner', 'Nuovo Cinema Paradiso',
       'Warrior', 'El laberinto del fauno', "C'est pas sorcier", 'Zodiac',
       'The Call', 'Warm Bodies', 'Jack the Giant Slayer', 'Breathe In',
       'Nightcrawler', 'Unpretty', 'Brothers', 'Changeling',
       'Relatos salvajes', 'L�t den r�tte komma in', 'Up in the Air',
       'Brooklyn', 'Hair', 'The Edge of Love', 'The Conjuring',
       '3:10 to Yuma', '25th Hour', 'The Assurance', 'Horra',
       'The Constant Gardener', "A Dog's Life", 'Kamea', 'Mou gaan dou',
       'Platoon', 'Unforgiven', 'Mr. Brooks', 'Bacheha-Ye aseman',
       'The Princess Bride', 'Raiders of the Lost Ark', 'Raging Bull',
       'The Dark Knight Rises', 'Reservoir Dogs',
       'Fittest on Earth: A Decade of Fitness', 'Taare Zameen Par',
       'Froning: The Fittest Man in History',
       'Fittest on Earth: The Story of the 2015 Reebok CrossFit Games',
       'Amadeus', 'Polytechnique', 'Behind the Walls',
       'Pirates of the Caribbean: Dead Men Tell No Tales', 'The Shining',
       'Kimi no na wa.', 'El Ni�o', 'Laaf Wa Dawaraan', 'Black', 'Hacker',
       'Get Out', 'Finding Nemo', 'Drag Me to Hell', 'Moonlight',
       'Oggy et les cafards', 'Doraemon', 'Tom and Jerry Tales',
       'The New Tom & Jerry Show', 'Popeye the Sailor',
       'The Sylvester & Tweety Mysteries', 'Taz-Mania', 'Smurfs',
       'The Tom and Jerry Show', 'Dragon Ball Z',
       'Dragon Ball: Doragon b�ru', 'Dragon Ball', 'Naruto: Shipp�den',
       'The Simpsons', 'The Adventures of Tintin', 'Shaun the Sheep',
       'The Bugs Bunny Show', 'Pinky and the Brain', 'Yu-Gi-Oh!',
       'Totally Spies!', 'Mr. Bean: The Animated Series',
       'El khoubz el hafi', 'Prison Break: Free', 'Noah', 'La haine',
       'American Hustle', 'Lion', 'Manchester by the Sea',
       'Nocturnal Animals', 'War for the Planet of the Apes',
       'Slumdog Millionaire', 'The Reef', 'The Pacifier',
       '2 Fast 2 Furious', 'Kon-Tiki', 'Dj�pi�', 'Passengers',
       'The Big Short', 'Panic Room', 'Once', 'Deep Web', 'Gifted',
       'Fantastic Mr. Fox', 'The Little Mermaid', 'Michiel de Ruyter',
       'Traitors', 'The Choice', 'Dear John', 'Untraceable', 'Keith',
       'Unbreakable', 'Love, Rosie', 'Spotlight', 'Resident Evil',
       'Bridge to Terabithia', 'Idi i smotri', 'Busanhaeng', 'Blackhat',
       'Shaun of the Dead', 'Die Hard', 'By�soku 5 senchim�toru',
       'American Psycho', 'Forgetting Sarah Marshall', 'Hannibal',
       'Touching the Void', 'When Harry Met Sally...', 'Groundhog Day',
       'Birdman or (The Unexpected Virtue of Ignorance)',
       'The Grand Budapest Hotel', 'Jagten', 'Annie Hall',
       'The Human Face of Big Data', 'Amores perros', 'Contratiempo',
       'No Country for Old Men', 'Nirgendwo in Afrika',
       'Fathers & Daughters', 'Hidden Figures', 'The Hangover',
       'Tau ming chong', 'Pretty Woman', 'Australia', 'Atlantic.',
       'Jerry Maguire', 'Elle', 'The Breakfast Club', 'RED',
       'The Big Lebowski', 'Black Swan', 'Crank', 'Drift',
       "L'iniziazione", 'Die Welle', 'Zwartboek',
       'The Cabin in the Woods', 'The Hurricane', 'The Descent', 'Taken',
       'Yip Man', 'The Blind Side', 'The Longest Yard', 'Chugyeogja',
       'The Best of Me', 'Superbad', 'The Insider', 'The Tourist',
       'The Lake House', 'Live Free or Die Hard', 'Little Miss Sunshine',
       'The River Why', "We're the Millers", 'The Elephant Man',
       'Julieta', 'Gone Baby Gone', 'Limitless', 'Me Before You',
       '10 Things I Hate About You', 'In Time', 'Bright Star',
       'Sahar el layaly', 'El secreto de sus ojos', 'Full Metal Jacket',
       'The General', 'Heat', 'Lucy', 'Frankenstein',
       '1001 Inventions and the Library of Secrets', 'Casino', 'Cave',
       'Indiana Jones and the Last Crusade', 'Nanny McPhee',
       'The Secret Life of Walter Mitty', 'The Stoning of Soraya M.',
       'Incendies', 'Proof', 'The Ugly Truth', 'Shot Caller',
       'The Wolverine', 'Bilal: A New Breed of Hero', 'Juno',
       '7-beon-bang-ui seon-mul',
       'The Lord of the Rings: The Return of the King',
       'The Count of Monte Cristo', 'The Avengers', 'Now You See Me',
       'If Only', 'The Accountant', 'Cloud Atlas', 'The Island', 'Friday',
       'Rampage', 'Good Bye Lenin!', 'Notting Hill', 'Sherlock Holmes',
       'Yes Man', 'Peaceful Warrior', 'Al Bayra, la vieille jeune fille',
       'Bruce Almighty', 'The Ultimate Gift', "Don't Breathe",
       'La piel que habito', 'Dom za vesanje', 'Speed', 'Silence',
       'The Family Man', 'Collide', 'Den 12. mann', 'Apocalypto',
       'Inside Man', 'Sherlock Jr.', 'Trois couleurs: Bleu',
       'The Machinist', 'Mr. Nobody', 'Fences', 'There Will Be Blood',
       'The Master', 'Vis a vis', 'The Mountain Between Us', 'Enemy',
       'Red Dragon', '13 Going on 30', 'El cuerpo', 'La migliore offerta',
       'Mientras duermes', 'Adrift', 'Faa yeung nin wa', 'The Artist',
       'Fargo', 'The Shape of Water',
       'Bom yeoreum gaeul gyeoul geurigo bom', 'Babam ve Oglum',
       'The Adventurer', 'Easy Street', 'The Pawnshop', 'Spy',
       'The Fireman', 'Lawrence of Arabia', 'The Cure', 'Salinui chueok',
       'A Quiet Place', 'Le dernier loup', 'En kongelig aff�re',
       'Testament of Youth', "The King's Speech", 'Ladri di biciclette',
       'Mommy', 'Awakenings', "La vie d'Ad�le", 'Blue Jasmine', 'Youth',
       'Blue Jay', 'Seven Pounds', 'Psycho', 'Scarface', 'Sicario',
       'Back to the Future', 'Waar', 'Beast', 'The Graduate',
       'The Lazarus Project', 'Hope', 'Majo no takky�bin', 'Dunkirk',
       'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',
       'Dead Poets Society', 'Mrs. Doubtfire', '50 First Dates',
       'Adoration', 'Misery', 'The Glass Castle', 'The Summit',
       'Gi-eok-ui bam', 'The Painted Veil', 'The First Time',
       'The Age of Innocence', 'Al final del t�nel', 'Loft',
       'Death Note: Desu n�to', 'Leave No Trace', 'Black Water', 'Jungle',
       'Identity', 'The Game', 'Perfect Sense', 'Detachment',
       'Half Nelson', 'Insomnia', 'Mystic River', 'Green Book',
       'Brokeback Mountain', 'Sense and Sensibility',
       'Sweeney Todd: The Demon Barber of Fleet Street', 'Phantom Thread',
       'Muzi v nadeji', 'The Favourite', 'La pianiste', 'Capharna�m',
       'On the Waterfront', 'Manbiki kazoku', '21 Grams', 'Frozen',
       'Gangs of New York', 'Backcountry', 'Short Term 12',
       '(500) Days of Summer', 'Perfetti sconosciuti', 'Primal Fear',
       'Philadelphia', 'Agora', 'The Illusionist',
       'The Killing of a Sacred Deer', 'Sully', 'Under the Silver Lake',
       'Werk ohne Autor', 'A Dangerous Method', 'The Lobster',
       'McFarland, USA', 'Anthropoid', 'Collateral',
       'The Legend of Zorro', 'The Social Network',
       'The Remains of the Day', 'Invictus', 'PK', 'Dangal',
       'The Ottoman Lieutenant', 'Bad Samaritan',
       'Three Billboards Outside Ebbing, Missouri', 'My Cousin Vinny',
       'Hotel Rwanda', 'Ex Machina', 'The Deer Hunter',
       'The Water Diviner', 'Boyhood', 'Apocalypse Now', 'Underground',
       'The Last Hangman', 'O Brother, Where Art Thou?', 'The Others',
       'Bronson', 'The Last of the Mohicans', 'Lady Bird',
       'The New World', 'Okuribito', 'Arctic', 'Durante la tormenta',
       'Midnight Express', 'I, Tonya', 'U-571', 'Crash',
       'House of Sand and Fog', 'Le scaphandre et le papillon',
       'Jane Eyre', 'Traffic', 'Gifted Hands: The Ben Carson Story',
       'Quills', 'Patch Adams', 'Mr. Bean: The Curse of Mr. Bean',
       'Icarus', 'Days of Heaven', 'Adaptation.', 'Papillon', 'Vikings',
       'Shakespeare in Love', 'Belle', 'Still Alice', 'The Dreamers',
       'Aus dem Nichts', 'Rango', "Gerald's Game", 'Demolition',
       "L'insulte", "Molly's Game", 'Once Upon a Time in America',
       'Alpha', 'The Hateful Eight', 'Meet the Parents', 'Rush',
       'Poseidon', 'El desconocido', 'Triangle', 'White Squall',
       'Unsere M�tter, unsere V�ter', 'American Pie', 'The Breed',
       'The Condemned', 'Rogue', 'The Beach', 'Six Days Seven Nights',
       'Los ojos de Julia', 'The Butler', 'The Martian', 'Gisaengchung',
       'Sukkar banat', "Ana Badi'a Ya Wadi'a", 'Dallas Buyers Club',
       'Rear Window', 'The Bourne Legacy', 'Tampopo', 'Source Code',
       'The Talented Mr. Ripley', 'The Snowman', 'Anna',
       'Jackie Chan Adventures', 'Revanche', 'Predestination',
       'Cool Hand Luke', 'Children of Men', 'The Man Who Knew Infinity',

In [12]:
watchlist_df['Title'].nunique()

999

In [13]:
watchlist_df['Title'].nunique(dropna=False)

999

In [14]:
watchlist_df.iloc[4]

Position                                              5
Const                                         tt0137523
Created                                       7/23/2016
Modified                                      7/23/2016
Description                                         NaN
Title                                        Fight Club
URL               https://www.imdb.com/title/tt0137523/
Title Type                                        movie
IMDb Rating                                         8.8
Runtime (mins)                                    139.0
Year                                               1999
Genres                                            Drama
Num Votes                                       1765736
Release Date                                  9/10/1999
Directors                                 David Fincher
Your Rating                                         8.0
Date Rated                                    7/21/2017
Name: 4, dtype: object

In [15]:
watchlist_df.iloc[4,0]

5

In [16]:
watchlist_df.iloc[0:4]

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
0,1,tt0332280,8/13/2015,8/13/2015,NaN,The Notebook,https://www.imdb.com/title/tt0332280/,movie,7.8,123.0,2004,"Drama, Romance",495765,5/20/2004,Nick Cassavetes,10.0,12/8/2016
1,2,tt0281358,8/13/2015,8/13/2015,NaN,A Walk to Remember,https://www.imdb.com/title/tt0281358/,movie,7.4,101.0,2002,"Drama, Romance",193482,1/23/2002,Adam Shankman,8.0,12/8/2016
2,3,tt0111161,7/23/2016,7/23/2016,NaN,The Shawshank Redemption,https://www.imdb.com/title/tt0111161/,movie,9.3,142.0,1994,Drama,2213171,9/10/1994,Frank Darabont,10.0,12/8/2016
3,4,tt0110912,7/23/2016,7/23/2016,NaN,Pulp Fiction,https://www.imdb.com/title/tt0110912/,movie,8.9,154.0,1994,"Crime, Drama",1737531,5/21/1994,Quentin Tarantino,5.0,7/21/2017

In [17]:
watchlist_df.sort_values('Title', ascending=True)

,Position,Const,Created,Modified,Description,Title,URL,Title Type,IMDb Rating,Runtime (mins),Year,Genres,Num Votes,Release Date,Directors,Your Rating,Date Rated
845,846,tt1022603,3/22/2019,3/22/2019,NaN,(500) Days of Summer,https://www.imdb.com/title/tt1022603/,movie,7.7,95.0,2009,"Comedy, Drama, Romance",455878,1/17/2009,Marc Webb,8.0,3/22/2019
697,698,tt0147800,1/17/2018,1/17/2018,NaN,10 Things I Hate About You,https://www.imdb.com/title/tt0147800/,movie,7.3,97.0,1999,"Comedy, Drama, Romance",282404,3/31/1999,Gil Junger,6.0,1/17/2018
56,57,tt0443649,12/8/2016,12/8/2016,NaN,"10,000 BC",https://www.imdb.com/title/tt0443649/,movie,5.1,109.0,2008,"Action, Adventure, Drama, Fantasy, History",122669,2/22/2008,Roland Emmerich,7.0,12/8/2016
707,708,tt1600740,2/2/2018,2/2/2018,NaN,1001 Inventions and the Library of Secrets,https://www.imdb.com/title/tt1600740/,short,8.5,13.0,2010,"Documentary, Short, Family",876,1/21/2010,Alan Deakins,8.0,2/2/2018
503,504,tt0050083,6/14/2017,6/14/2017,NaN,12 Angry Men,https://www.imdb.com/title/tt0050083/,movie,8.9,96.0,1957,Drama,646627,4/10/1957,Sidney Lumet,6.0,6/14/2017
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250,251,tt1529358,12/8/2016,12/8/2016,NaN,Zoj taht al-talab,https://www.imdb.com/title/tt1529358/,movie,5.3,109.0,1985,"Comedy, Drama",268,12/31/1985,Adel Sadiq,NaN,NaN
57,58,tt2948356,12/8/2016,12/8/2016,NaN,Zootopia,https://www.imdb.com/title/tt2948356/,movie,8.0,108.0,2016,"Animation, Adventure, Comedy, Crime, Family, M...",408728,2/11/2016,"Rich Moore, Jared Bush, Byron Howard",10.0,6/29/2016
674,675,tt0389557,11/14/2017,11/14/2017,NaN,Zwartboek,https://www.imdb.com/title/tt0389557/,movie,7.7,145.0,2006,"Drama, Thriller, War",70311,9/1/2006,Paul Verhoeven,7.0,11/15/2017
354,355,tt1038988,1/28/2017,1/28/2017,NaN,[Rec],https://www.imdb.com/title/tt1038988/,movie,7.4,78.0,2007,"Horror, Mystery, Thriller",159055,8/29/2007,"Jaume Balaguer�, Paco Plaza",4.0,1/28/2017
377,378,tt0111857,2/5/2017,2/5/2017,NaN,� la recherche du mari de ma femme,https://www.imdb.com/title/tt0111857/,movie,7.6,88.0,1995,Comedy,35,6/7/1995,Mohamed Abderrahman Tazi,NaN,NaN

In [18]:
watchlist_df.isnull().sum()

Position             0
Const                0
Created              0
Modified             0
Description       1000
Title                0
URL                  0
Title Type           0
IMDb Rating          0
Runtime (mins)      42
Year                 0
Genres               1
Num Votes            0
Release Date        13
Directors           50
Your Rating        335
Date Rated         335
dtype: int64

In [19]:
watchlist_df.dropna(inplace=True)

In [20]:
watchlist_df.isnull().sum()

Position          0.0
Const             0.0
Created           0.0
Modified          0.0
Description       0.0
Title             0.0
URL               0.0
Title Type        0.0
IMDb Rating       0.0
Runtime (mins)    0.0
Year              0.0
Genres            0.0
Num Votes         0.0
Release Date      0.0
Directors         0.0
Your Rating       0.0
Date Rated        0.0
dtype: float64